server:
  session-timeout: 1800
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /upms

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/**/*Mapper.xml
  type-aliases-package: com.ming.upms


# Spring 配置
spring:
  application:
    name: ming-upms
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    #禁用缓存
    cache: false
  profiles:
    active: dev

# actuator监控
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always